# Generated by Django 5.2.1 on 2025-05-19 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False, unique=True)),
                ('is_day_off', models.BooleanField(default=False)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('dislikes', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_type', models.CharField(choices=[('GridView1', 'Günlük Menü'), ('GridViewGltensiz', 'Glutensiz Menü'), ('GridViewVegan', 'Vegan Menü'), ('GridViewVej', 'Vejetaryen Menü')], max_length=40)),
                ('item_name', models.CharField(max_length=100)),
                ('calorie', models.PositiveIntegerField(blank=True, null=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='menu.menu')),
            ],
        ),
    ]
