# Generated by Django 5.2.1 on 2025-05-19 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, unique=True, verbose_name='Bus Number')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_day', models.CharField(choices=[('Weekday', 'Hafta İçi'), ('Saturday', 'Cumartesi'), ('Sunday', 'Pazar')], max_length=9, verbose_name='Trip Day')),
                ('is_start_from_iyte', models.BooleanField(default=False, verbose_name='Starts from IYTE')),
                ('departure_station', models.CharField(max_length=100, verbose_name='Departure Station')),
                ('arrival_station', models.CharField(max_length=100, verbose_name='Arrival Station')),
                ('departure_time', models.TimeField()),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='bus.bus')),
            ],
        ),
    ]
