# Generated by Django 5.2.1 on 2025-05-19 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='message_action',
            field=models.BooleanField(default=False),
        ),
    ]
